swagger: "2.0"
info:
  version: 1.0.0
  title: Authentication API
  description: Collection of endpoints to interact with user's auth session.
host: localhost
basePath: /
schemes:
  - https
security:
  - Bearer: []
paths:
  "/logout":
    x-swagger-router-controller: AuthenticationController
    post:
      operationId: logout
      summary: Execute the logout
      description: Delete user's active session and tokens.
      responses:
        "200":
          description: Logout succeeded
          schema:
            $ref: "#/definitions/SuccessResponse"
          examples:
            application/json:
              message: "ok"
  "/user-identity":
    x-swagger-router-controller: AuthenticationController
    get:
      operationId: getUserIdentity
      summary: Get stored user's identity
      description: Returns the user's identity stored during the login phase
      responses:
        "200":
          description: Found.
          schema:
            $ref: "#/definitions/UserIdentity"
          examples:
            application/json:
              family_name: "Rossi"
              fiscal_code: "TMMEXQ60A10Y526X"
              name: "Mario"
              spid_email: "preferred@example.com"
              spid_mobile_phone: "1234567890"
        "401":
          description: Bearer token null or expired.
definitions:
  SuccessResponse:
    type: object
    properties:
      message:
        type: string
  SpidUserIdentity:
    type: object
    title: SPID User Identity
    description: Describes the user's profile while it's authenticated with Spid.
    properties:
      family_name:
        type: string
      name:
        type: string
      spid_mobile_phone:
        type: string
        minLength: 1
    required:
      - family_name
      - name
      - spid_mobile_phone
  CieUserIdentity:
    type: object
    title: CIE User Identity
    description: Describes the user's profile while it's authenticated with CIE.
    properties:
      family_name:
        type: string
      name:
        type: string
      date_of_birth:
        type: string
        format: date
    required:
      - family_name
      - name
      - date_of_birth
  UserIdentity:
    x-one-of: true
    allOf:
      - $ref: "#/definitions/SpidUserIdentity"
      - $ref: "#/definitions/CieUserIdentity"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header